### ISSUE TITLE
epub creation fails for viswadarsanamupa026136mbp

### ISSUE THREAD

**Issue by mikemccabe** [internetarchive/epub#22]
http://www.archive.org/details/viswadarsanamupa026136mbp

http://www.us.archive.org/log_show.php?task_id=70705437

<--------------- Module EPUB (v31672 2011Jan28 09:29) Starting  PST: 2011-01-28 09:29:51 ------------------

[ PST: 2011-01-28 09:29:51 ] Executing: rm -rf /tmp/derive-viswadarsanamupa026136mbp-EPUB/
[ PST: 2011-01-28 09:29:51 ] Executing: mkdir /tmp/derive-viswadarsanamupa026136mbp-EPUB/
[ PST: 2011-01-28 09:29:51 ] Executing: gunzip -c /tmp/derive/viswadarsanamupa026136mbp/viswadarsanamupa026136mbp_abbyy.gz > /tmp/derive-viswadarsanamupa026136mbp-EPUB/viswadarsanamupa026136mbp_abbyy.xml
Found TOC in Open Library for this book
[ PST: 2011-01-28 09:29:53 ] Executing: PATH=/petabox/sw/bin:$PATH LD_LIBRARY_PATH=/petabox/sw/lib/kakadu python /petabox/www/datanode/epub/convert_iabook.py  --toc='[{"pagenum":"IX","level":1,"type":{"key":"\/type\/toc_item"},"title":"\u0c2e\u0c41\u0c02\u0c26\u0c41\u0c2e\u0c3e\u0c1f"},{"pagenum":"1","level":1,"label":"1","type":{"key":"\/type\/toc_item"},"title":"\u0c09\u0c2a\u0c4b\u0c26\u0c4d\u0c18\u0c3e\u0c24\u0c02"},{"pagenum":"12","level":1,"label":"2","type":{"key":"\/type\/toc_item"},"title":"\u0c17\u0c4d\u0c30\u0c40\u0c15\u0c41\u0c32 \u0c2a\u0c42\u0c30\u0c4d\u0c35 \u0c30\u0c02\u0c17\u0c02"},{"pagenum":"22","level":1,"label":"3","type":{"key":"\/type\/toc_item"},"title":"\u0c24\u0c4a\u0c32\u0c3f \u0c17\u0c4d\u0c30\u0c40\u0c15\u0c41 \u0c24\u0c24\u0c4d\u0c35\u0c35\u0c47\u0c24\u0c4d\u0c24 \u0c25\u0c47\u0c32\u0c3f\u0c38\u0c4d"},{"pagenum":"30","level":1,"label":"4","type":{"key":"\/type\/toc_item"},"title":"\u0c25\u0c47\u0c32\u0c3f\u0c38\u0c4d \u0c36\u0c3f\u0c37\u0c4d\u0c2f \u0c2a\u0c4d\u0c30\u0c36\u0c3f\u0c37\u0c4d\u0c2f\u0c41\u0c32\u0c41"},{"pagenum":"38","level":1,"label":"5","type":{"key":"\/type\/toc_item"},"title":"\u0c2d\u0c3e\u0c35\u0c35\u0c3e\u0c26 \u0c2a\u0c3f\u0c24\u0c3e\u0c2e\u0c39\u0c41\u0c21\u0c41 \u0c2a\u0c3f\u0c24\u0c3e\u0c17\u0c30\u0c38\u0c4d"},{"pagenum":"47","level":1,"label":"6","type":{"key":"\/type\/toc_item"},"title":"\u0c28\u0c3f\u0c30\u0c3f\u0c02\u0c24\u0c30 \u0c2a\u0c30\u0c3f\u0c35\u0c30\u0c4d\u0c24\u0c28\u0c35\u0c3e\u0c26\u0c3f \u0c39\u0c46\u0c30\u0c3e\u0c15\u0c4d\u0c32\u0c3f\u0c1f\u0c38\u0c4d"},{"pagenum":"53","level":1,"label":"7","type":{"key":"\/type\/toc_item"},"title":"\u0c2a\u0c3e\u0c30\u0c2d\u0c4c\u0c24\u0c3f\u0c15 \u0c24\u0c3e\u0c24\u0c4d\u0c35\u0c3f\u0c15\u0c41\u0c21\u0c41 \u0c2a\u0c3e\u0c30\u0c4d\u0c2e\u0c46\u0c28\u0c3f\u0c21\u0c40\u0c38\u0c4d"},{"pagenum":"62","level":1,"label":"8","type":{"key":"\/type\/toc_item"},"title":"\u0c2c\u0c39\u0c41\u0c38\u0c24\u0c4d\u0c24\u0c3e\u0c35\u0c3e\u0c26\u0c41\u0c32\u0c41: \u0c0e\u0c02\u0c2a\u0c3f\u0c21\u0c4b\u0c15\u0c4d\u0c32\u0c40\u0c38\u0c4d, \u0c05\u0c28\u0c17\u0c4d\u0c1c\u0c3e\u0c17\u0c30\u0c38\u0c4d"},{"pagenum":"68","level":1,"label":"9","type":{"key":"\/type\/toc_item"},"title":"\u0c21\u0c46\u0c2e\u0c4a\u0c15\u0c4d\u0c30\u0c1f\u0c3f\u0c38\u0c4d \u0c05\u0c23\u0c41\u0c35\u0c3e\u0c26\u0c02"},{"pagenum":"73","level":1,"label":"10","type":{"key":"\/type\/toc_item"},"title":"\u0c38\u0c4b\u0c2b\u0c3f\u0c37\u0c4d\u0c1f\u0c41\u0c32 \u0c35\u0c3e\u0c26 \u0c2c\u0c4d\u0c30\u0c39\u0c4d\u0c2e\u0c4b\u0c2a\u0c3e\u0c38\u0c28"},{"pagenum":"83","level":1,"label":"11","type":{"key":"\/type\/toc_item"},"title":"\u0c38\u0c4b\u0c15\u0c4d\u0c30\u0c1f\u0c40\u0c38\u0c4d \u0c09\u0c1c\u0c4d\u0c35\u0c32 \u0c1c\u0c40\u0c35\u0c3f\u0c24\u0c17\u0c3e\u0c27"},{"pagenum":"99","level":1,"label":"12","type":{"key":"\/type\/toc_item"},"title":"\u0c38\u0c4d\u0c35\u0c3e\u0c2a\u0c4d\u0c28\u0c3f\u0c15 \u0c38\u0c3e\u0c2e\u0c4d\u0c30\u0c3e\u0c1f\u0c4d\u0c1f\u0c41, \u0c06\u0c26\u0c30\u0c4d\u0c36\u0c35\u0c3e\u0c26\u0c3f \u0c2a\u0c4d\u0c32\u0c47\u0c1f\u0c4b"}]' --epub --document='viswadarsanamupa026136mbp' 'viswadarsanamupa026136mbp' '/tmp/derive/viswadarsanamupa026136mbp/' '/tmp/derive/viswadarsanamupa026136mbp/viswadarsanamupa026136mbp.epub'  2>&1
Traceback (most recent call last):
  File "/petabox/www/datanode/epub/convert_iabook.py", line 183, in 
    main(sys.argv[1:])
  File "/petabox/www/datanode/epub/convert_iabook.py", line 162, in main
    iabook_to_epub.process_book(iabook, ebook)
  File "/usr/local/petabox/www/datanode/epub/iabook_to_epub.py", line 210, in process_book
    region=region)
  File "/usr/local/petabox/www/datanode/epub/iarchive.py", line 237, in get_page_image
    kdu_reduce)
  File "/usr/local/petabox/www/datanode/epub/iarchive.py", line 312, in image_from_zip
    + cvt_to_out)
OSError: [Errno 24] Too many open files

**Comment by mikemccabe** [comment]
files copied to /home/mccabe/s/archive/books/viswadarsanamupa026136mbp

**Comment by mikemccabe** [comment]
book now rederived w/o ocr, so this particular book no longer has this issue.
